### ISSUE TITLE
Mobile snapping

### ISSUE THREAD

**Issue by NodexTech** [neilellis/rendercat#1]
Hi there, great tool, you have an issue on Mobile / Tablet setting. If you view https://www.nodex.co.uk on a mobile or tablet then it renders properly using media queries (responsive), if however you render it with rendercat it seems to zoom in on the top left corner of the page and snap the device dimensions as opposed to using the media queries.

I know that Nodex website works fine with phantomjs as I have used it hundreds of times so I would think the bug lay somewhere in the options you're giving it

**Comment by neilellis** [comment]
Hi and many thanks for reporting the bug. Looking into it right now. 

At the moment I actually use SlimerJS as the default for command line based rendering which is based on Firefox but API compatible with PhantomJS. 

Many thanks
Neil

**Comment by neilellis** [comment]
Latest version has fix for mobile, thanks again! : http://rendercat-snapshot-1.neilellis.cont.tutum.io/#url=http%3A%2F%2Fwww.nodex.co.uk&size=full&screen=mobile&delay=1&type=png&freshness=cached&quality=high
